/**
 * User API
 * A simple API to manage users
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface CreateUserRequestDto { 
    /**
     * The user name
     */
    name: string;
    /**
     * The user email
     */
    email: string;
    /**
     * The user phone
     */
    phone: string;
}

